window.BE_FINDINGS=[
{id:'light',finding:'Morning light moves your clock.',cite:'(Current Biology, 2013)',act:'Ten minutes outside before screens \u2014 a window counts if that\u2019s what today allows.',why:'A week under natural light re-synced campers\u2019 body clocks to the sun; even a weekend outdoors did most of the work.'},
{id:'nature',finding:'About two hours a week in nature is where reported health and wellbeing rise.',cite:'(Scientific Reports, 2019)',act:'Twenty minutes somewhere green, at your pace. Split it however you like.',why:'In ~20,000 people, the benefit appeared at 120 minutes a week \u2014 in one visit or many small ones.'},
{id:'ties',finding:'Strong social ties are among the best-studied predictors of a long life.',cite:'(PLoS Medicine, 2010)',act:'One unhurried check-in \u2014 a call, a walk, a hug asked for, a meal at one table.',why:'Across 148 studies of 308,849 people, stronger relationships meant ~50% higher likelihood of survival \u2014 an effect in smoking\u2019s league.'},
{id:'breath',finding:'Long exhales settle the body faster than watching thoughts.',cite:'(Cell Reports Medicine, 2023)',act:'Five minutes of sighing breaths \u2014 in once, then out long and slow.',why:'A month-long trial: 5 minutes of exhale-weighted breathing daily improved mood more than meditation. Early evidence, honestly \u2014 about 100 people.'},
{id:'naming',finding:'Naming a feeling quiets the brain\u2019s alarm.',cite:'(Psychological Science, 2007)',act:'When something surges today, try one plain word for it \u2014 said kindly, to yourself.',why:'In brain scans, putting feelings into words dampened the amygdala and woke the naming part of the cortex.'},
{id:'pollen',finding:'Three of every four food crop types lean on pollinators.',cite:'(FAO)',act:'Plant or tend one flowering thing this week \u2014 a pot on a sill counts.',why:'Honest footnote: staples like wheat and rice self-suffice; what pollinators keep is most of the colorful, vitamin-rich food \u2014 about a third of production.'},
{id:'touch',finding:'Consensual touch eases pain and low mood.',cite:'(Nature Human Behaviour, 2024)',act:'One embrace today \u2014 asked for first, and only if you\u2019d like one. A hand on your own heart counts too.',why:'A meta-analysis of 137 studies (~13,000 people): touch interventions eased pain, depression, and anxiety in adults. Always consensual \u2014 asking is part of the medicine.'},
{id:'laugh',finding:'A shared giggle is bonding chemistry.',cite:'(Phil. Trans. R. Soc. B, 2022)',act:'Trade one thing that made you laugh with someone \u2014 no screen required.',why:'Laughing together upregulates the brain\u2019s endorphin system \u2014 the same warmth-and-trust chemistry primates get from grooming, shared at group scale.'}
];
